version: '3.3'
services:
        db:
                build:
                        context: .
                        dockerfile: Dockerfile_db
                env_file:
                        - postgres.env
                volumes:
                        - type: volume
                          source: sql_data_os_monitor
                          target: /var/lib/postgresql/data
                          volume:
                                  nocopy: true

                                  #                networks:
                                  #                        osnet_2:



        shiny:
                build: 
                        context: .
                        dockerfile: Dockerfile_shiny
                ports:
                        - "3839:3839"
                volumes:
                        - type: volume
                          source: shiny_logs
                          target: /var/log/shiny-server
                        - type: volume
                          source: shiny_bookmarks
                          target: /var/lib/shiny-server/bookmarks
                          #                networks:
                          #                        osnet_2:
                depends_on:
                        - db
                environment:
                        - APPLICATION_LOGS_TO_STDOUT=true

volumes:
        sql_data_os_monitor:
                external: true
        shiny_logs:
                external: true
        shiny_bookmarks:
                external: true

                #networks:
                #        osnet_2:
                #                external: true

